# Generated by Django 3.2.13 on 2022-04-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='image',
            new_name='featured_image',
        ),
    ]
