# Generated by Django 3.2.13 on 2022-05-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0005_auto_20220504_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('new_specification', models.TextField()),
            ],
        ),
    ]
